version: 2.1

aliases:
  - &ci-build-image quay.io/yeebase/ci-build:7.3
  - &workspace_root ~/workspace

  - &save_composer_cache
    key: composer-cache-v1-{{ .Branch }}-{{ checksum "composer.json" }}
    paths:
      - /composer/cache-dir

  - &restore_composer_cache
    keys:
      - composer-cache-v1-{{ .Branch }}-{{ checksum "composer.json.ci" }}
      - composer-cache-v1-{{ .Branch }}-
      - composer-cache-v1-

  - &attach_workspace
     at: *workspace_root

  - &persist_to_workspace
    root: .
    paths:
      - .

jobs:
  checkout:
    docker:
      - image: *ci-build-image
    environment:
      COMPOSER_CACHE_DIR: /composer/cache-dir
    steps:
      - checkout
      - restore_cache: *restore_composer_cache

      - run: |
          mkdir rabbit
          shopt -s extglob dotglob
          mv !(rabbit) rabbit
          shopt -u dotglob
          cp rabbit/composer.json.ci composer.json
          cp rabbit/phpcs.xml.dist phpcs.xml.dist
          cp rabbit/unitTests.xml unitTests.xml
          composer update --ignore-platform-reqs

      - save_cache: *save_composer_cache
      - persist_to_workspace: *persist_to_workspace

  lint:
    working_directory: *workspace_root
    docker:
      - image: *ci-build-image
    steps:
      - attach_workspace: *attach_workspace
      - run: bin/phpcs rabbit/Classes

  unit-tests:
    working_directory: *workspace_root
    docker:
      - image: *ci-build-image
    steps:
      - attach_workspace: *attach_workspace
      - run: bin/phpunit -c unitTests.xml

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout:
        filters:
          branches:
            ignore: /dependabot.*/
      - lint:
          requires:
            - checkout
      - unit-tests:
          requires:
            - checkout

  build_and_test_dependabot:
    jobs:
      - hold:
          type: approval
          filters:
            branches:
              only: /dependabot.*/
      - checkout:
          requires:
            - hold
      - lint:
          requires:
            - checkout
      - unit-tests:
          requires:
            - checkout